# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use Python 3.9 environment
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt || true
      - run:
          name: Run tests
          command: |
            python -m unittest discover -s tests
